ex 17 implemented
FOAP-NetMind-2022/beetlepush pull request #64
Opened 2022-10-14 11:06 UTC by omiras

2022-10-15 09:41 UTC, Andreu-G commented on public/js/translations.js
> +        'methodTitle': `Crate a new array with the bugs which name has more than 5 letters`,
```suggestion
        'methodTitle': `Create a new array with the name of the bugs that have more than 5 letters`,
```

2022-10-15 09:41 UTC, Andreu-G commented on public/js/translations.js
> +        'instructions': `<div>We like large bugs names, so in this exercise, use the <strong>filter</strong> method to achieve it</div>`,
```suggestion
        'instructions': `<div>We like long bugs names, so in this exercise, use the <strong>filter()</strong> method to achieve it</div>`,
```

2022-10-15 09:41 UTC, Andreu-G commented on public/js/translations.js
> +        'methodTitle': `Crea un nuevo array con el nombre de los bichos que tienen más de 5 letras`,
```suggestion
        'methodTitle': `Crea un nuevo array con el nombre de los insectos que tienen más de 5 letras`,
```

2022-10-15 09:41 UTC, Andreu-G commented on public/js/translations.js
> +        'methodHelp': `Filtra los bichos`,
```suggestion
        'methodHelp': `Filtra los insectos`,
```

2022-10-15 09:41 UTC, Andreu-G commented on public/js/translations.js
> +        'desc': `El método filter crea un nuevo array con todos elementos que pasan la función de test.`,
```suggestion
        'desc': `El método filter() crea un nuevo array con todos elementos que pasan la función de test.`,
```

2022-10-15 09:41 UTC, Andreu-G commented on public/js/translations.js
> +        'instructions': `<div>Nos gustan los animales con nombres largos. Usa el método <strong>filter</strong> para pasar este ejercicio.</div>`,
```suggestion
        'instructions': `<div>Nos gustan los insectos con nombres largos. Usa el método <strong>filter()</strong> para pasar este ejercicio.</div>`,
```

2022-10-15 09:41 UTC, Andreu-G commented on public/js/levels.js
> +        </grass>
```suggestion
        </grass>
        <grass>
          <spider class="dance">
        </grass>
```

2022-10-15 09:41 UTC, Andreu-G commented on public/js/levels.js
> +          <spider>
```suggestion
          <spider class="dance">
```

2022-10-15 09:41 UTC, Andreu-G commented on public/js/levels.js
> +      myGrassSolution : ['butterfly','dragonFly'],
```suggestion
      myGrassSolution : ['butterfly','dragonFly','spider'],
```
Spider has 6 letters :)

2022-10-15 09:41 UTC, Andreu-G commented on public/js/levels.js
> +      doThis: "Crate a new array with the bugs which name has more than 5 letters",
```suggestion
      doThis: "Create a new array with the name of the bugs that have more than 5 letters",
```

2022-10-15 09:54 UTC, Andreu-G requested changes
Other than the comments above, I also believe the *largeNames* variable is currently useless.

![Screenshot_000750](https://user-images.githubusercontent.com/105077715/195980091-4eb47145-8949-4ff2-a85d-3ed52febd7fa.png)

As you can see, the code does not complete. I believe this is because you're not actually changing the *myGrass* variable, but instead the *largeNames* variable, which the code doesn't care about.

![Screenshot_000751](https://user-images.githubusercontent.com/105077715/195980163-cb61ca33-3d9a-454d-a7d4-1bda2e5b9ac9.png)

If you instead modify *myGrass* directly, the level is completed.

2022-10-15 09:57 UTC, Andreu-G commented on public/js/levels.js
> +      myGrass : "var myGrass = ['worm','butterfly','bee','dragonFly','spider'];\n\nvar largeNames;",
```suggestion
      myGrass : "var myGrass = ['worm','butterfly','bee','dragonFly','spider'];\n\nvar longNames;",
```

2022-10-15 09:57 UTC, Andreu-G commented on public/js/levels.js
> +      variableToCheck: "myGrass",
```suggestion
      variableToCheck: "longNames",
```

2022-10-15 09:58 UTC, Andreu-G commented
With these 2 last changes, everything should work perfectly.

2022-10-23 09:12 UTC, omiras commented
OMG thank you @Andreu-G , I think that I even did not test it, I was too confident!

2022-10-23 09:12 UTC, merged